

# 1 The newsvendor problem (integer formulation)

Each morning, the newsvendor must decide how many copies $u \in \{1, 2,…,u^{♯}\}$ of the day’s paper to order. The variable u is called control.

During the day, the newsvendor will meet an unknown demand $w  \in \{1,2,...,w^{♯}\}$ . The variable w is called uncertainty.

The newsvendor faces an economic tradeoff:

- He pays the unitary purchasing cost c per copy, when he orders stock;

- He sells a copy at price p;

- if he remains with an unsold copy, it is worthless (perishable good).

Therefore, the newsvendor’s costs are (where w is a possible value of the demand)

$$j(u,w) = cu-p\min\{u,w\}$$

The newsvendor’s payoff is $−j(u,w)$.

Now, we introduce a random variable W, where $W : Ω →\{1, 2,…,w^{♯}\}$. Here, $Ω$ is an underlying probability space, equipped with a probability $ℙ$. We suppose that the newsvendor knows the probability distribution $\mathbb{P}_{W}$ of the demand $W$.

Thus equipped, we consider the stochastic optimization problem of expected costs minimization:

$$\min_{w  \in \{1,2,...,w^{♯}\}} J(u) = \mathbb{E}_{\mathbb{P}}[j(u,W)]$$


In [110]:
import numpy as np

# Demand

wsharp = 100;  # No larger, else the Poisson distribution cannot be computed
wflat = 1;
demand = np.zeros((1,wsharp));
for i in range(wsharp):
    demand[0][i] = i+1;

# Control

control = np.zeros((1,wsharp+1));
for i in range(wsharp+1):
    control[0][i] = i+1;

# Criterion / costs 

cc = 1;
pp = 10*cc;

# cc=1; 
# pp=1.1*cc; 

# avoid that cc/pp is the inverse of an integer when the distribution of demand is uniform

ones_demand = np.zeros((1,wsharp));
for i in range(wsharp):
    ones_demand[0][i] = 1;
    
ones_control = np.zeros((1,wsharp+1));
for i in range(wsharp+1):
    ones_control[0][i] = 1;
    
costs = np.matmul(cc*np.transpose(control),ones) - pp*np.minimum(np.matmul(np.transpose(ones_control),demand),np.matmul(np.transpose(control),ones_demand));

# One row by control, one column by demand


[[  -9.   -9.   -9. ...   -9.   -9.   -9.]
 [  -8.  -18.  -18. ...  -18.  -18.  -18.]
 [  -7.  -17.  -27. ...  -27.  -27.  -27.]
 ...
 [  89.   79.   69. ... -881. -891. -891.]
 [  90.   80.   70. ... -880. -890. -900.]
 [  91.   81.   71. ... -879. -889. -899.]]


We will consider different demand distributions.

# 1.1 The demand distribution is uniform

First, we suppose that the demand distribution ℙW is uniform as follows.

In [112]:
probab = ones_demand;
probab = probab/np.sum(probab);
print(probab)

[[0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01 0.01
  0.01 0.01]]
